### ISSUE TITLE
Error inflating class com.goka.blurredgridmenu.BlurringView

### ISSUE THREAD

**Issue by javierpe** [gotokatsuya/BlurredGridMenu#2]
When 

FragmentTransaction tx = getSupportFragmentManager().beginTransaction();
tx.replace(R.id.main_frame, mGridMenuFragment);
tx.addToBackStack(null);
tx.commit();

**Comment by gotokatsuya** [comment]
Hi @FranciscoJavierPRamos 

Thank you for using this library.

Did you get this problem when you ran my sample project ?

**Comment by wangpeiyuan** [comment]
@gotokatsuya I have the sample problem

**Comment by gotokatsuya** [comment]
@cock-tail 

Thank you for your contact.

OK. I'm gonna look over BlurringView class.

**Comment by wangpeiyuan** [comment]
@gotokatsuya I know what caused this problem.Didn't find class "android.support.v8.renderscript.RenderScript" ,add renderscript-v8.jar can  resolve this problem

**Comment by gotokatsuya** [comment]
@cock-tail 

Thank you so much for your advice !

But, it works on my env without renderscript-v8.jar.

These websites may help you. Have you looked these ?

http://developer.android.com/guide/topics/renderscript/compute.html

http://stackoverflow.com/questions/19658145/how-to-use-the-renderscript-support-library-with-gradle

**Comment by wangpeiyuan** [comment]
@gotokatsuya I didn't see it,but it is better than my way.Thank you!
