### ISSUE TITLE
problem duplicate res file with new android studio

### ISSUE THREAD

**Issue by alexodus** [gotokatsuya/BlurredGridMenu#3]
C:\xxxx\app\build\intermediates\res\debug\drawable-hdpi-v4\ic_launcher.png: error: Duplicate file.
C:\xxxx\app\build\intermediates\res\debug\drawable-hdpi\ic_launcher.png: Original is here. The version qualifier may be implied.

Please remove this resource file

**Comment by gotokatsuya** [comment]
@alexodus 

OK. I'm gonna remove these files.

**Comment by gotokatsuya** [comment]
@alexodus 

https://github.com/gotokatsuya/BlurredGridMenu/commit/39b4eec83f74f50e6692ef5caf5ff6ffc0b0b877

Is it OK ?

If you like this commit, I will release BlurredGridMenu as v1.0.2.

**Comment by alexodus** [comment]
I cannot test, but it's ok. Thanks
Il 29/giu/2015 16:01, "goka" notifications@github.com ha scritto:

**Comment by gotokatsuya** [comment]
@alexodus You're welcome !

If you get a problem, please let me know soon.

**Comment by gotokatsuya** [comment]
Please use `compile 'com.github.goka.blurredgridmenu:blurredgridmenu:1.0.2'`
