### ISSUE TITLE
Error:(108, 0) Cannot call getBootClasspath() before setTargetInfo() is called

### ISSUE THREAD

**Issue by sarthak3154** [gotokatsuya/BlurredGridMenu#6]
When importing blurredgridmenu module to another project this error comes into being.
Even when trying copying this module to another project, it says "Cannot create class file"

**Comment by gotokatsuya** [comment]
@sarthak3154 

Sorry for late reply.

Hmm, You use gradle ?

```
dependencies {
    compile 'com.github.goka.blurredgridmenu:blurredgridmenu:1.0.2'
}
```
